# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YVideo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YVideo


  pod 'AJNetworking'
  pod 'YYKit'
  pod 'UITableView-NXEmptyView', '~> 0.1.7'
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'MJRefresh'
  pod 'Masonry'
  

  target 'YVideoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YVideoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
